#define compiler 
CC = gcc

# compiler flags:
CFLAGS  = -m32

# the build target executable:
TARGET = VulnApp

all: $(TARGET)

$(TARGET): $(TARGET).c
        $(CC) $(CFLAGS) -o $(TARGET) $(TARGET).c


